const INSERT_PIN_COMMAND_NAME = 'INSERT_PIN_COMMAND_NAME';
const DEPOSIT_MONEY_COMMAND_NAME = 'DEPOSIT_MONEY_COMMAND_NAME';
const WITHDRAW_MONEY_COMMAND_NAME = 'WITHDRAW_MONEY_COMMAND_NAME';
const CREATE_TODO_COMMAND_NAME = 'CREATE_TODO_COMMAND_NAME';

const GET_ALL_TODOS_QUERY_NAME = 'GET_ALL_TODOS_QUERY_NAME';

export {
  CREATE_TODO_COMMAND_NAME,
  GET_ALL_TODOS_QUERY_NAME,
  INSERT_PIN_COMMAND_NAME,
  DEPOSIT_MONEY_COMMAND_NAME,
  WITHDRAW_MONEY_COMMAND_NAME,
};
