const INSERT_PIN_COMMAND_NAME = 'INSERT_PIN_COMMAND_NAME';
const DEPOSIT_MONEY_COMMAND_NAME = 'DEPOSIT_MONEY_COMMAND_NAME';
const WITHDRAW_MONEY_COMMAND_NAME = 'WITHDRAW_MONEY_COMMAND_NAME';
const CREATE_TODO_COMMAND_NAME = 'CREATE_TODO_COMMAND_NAME';
const SEND_EMAIL_VERIFICATION_COMMAND_NAME = 'SEND_EMAIL_VERIFICATION_COMMAND_NAME';

const GET_ALL_TODOS_QUERY_NAME = 'GET_ALL_TODOS_QUERY_NAME';
const GET_CUSTOMER_BY_ID_QUERY_NAME = 'GET_CUSTOMER_BY_ID_QUERY_NAME';
const GET_ACCOUNT_QUERY_NAME = 'GET_ACCOUNT_QUERY_NAME';
const GET_CUSTOMER_BY_EMAIL_QUERY_NAME = 'GET_CUSTOMER_BY_EMAIL_QUERY_NAME';

export {
  CREATE_TODO_COMMAND_NAME,
  GET_ALL_TODOS_QUERY_NAME,
  INSERT_PIN_COMMAND_NAME,
  DEPOSIT_MONEY_COMMAND_NAME,
  WITHDRAW_MONEY_COMMAND_NAME,
  SEND_EMAIL_VERIFICATION_COMMAND_NAME,
  GET_CUSTOMER_BY_ID_QUERY_NAME,
  GET_ACCOUNT_QUERY_NAME,
  GET_CUSTOMER_BY_EMAIL_QUERY_NAME,
};
