version: '3.8'

services:
  todo-frontend:
    build:
      context: frontend/
    ports:
      - '3000:3000'
    networks:
      - bitloops
    depends_on:
      - todo-backend

  todo-backend:
    build:
      context: backend/
    ports:
      - '8081:8081'
      - '8082:8082'
    networks:
      - bitloops
    depends_on:
      - bl-mongo
      - bl-postgres
      - bl-nats

  bl-mongo:
    image: mongo:5
    container_name: mongo1
    command: ['--replSet', 'my-replica-set', '--bind_ip_all', '--port', '30001']
    volumes:
      - bl-mongo_data:/data/db
    ports:
      - 30001:30001
    healthcheck:
      test: test $$(echo "rs.initiate({_id:'my-replica-set',members:[{_id:0,host:\"mongo1:30001\"}]}).ok || rs.status().ok" | mongo --port 30001 --quiet) -eq 1
      interval: 10s
      start_period: 30s
    networks:
      - bitloops

  bl-nats:
    image: nats:latest
    container_name: nats
    ports:
      - '4222:4222'
      - '8222:8222'
      - '6222:6222'
      - '4223:4223'
      - '6223:6223'
      - '8223:8223'
    volumes:
      - bl-nats_data:/usr/share/docker/nats-server
    networks:
      - bitloops
    command: ['-js', '-m', '8223']

  bl-postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: iam
      POSTGRES_USER: user
    ports:
      - '5432:5432'
    volumes:
      - bl-postgres_data:/usr/share/docker/postgresql
    networks:
      - bitloops

  bl-envoy:
    build:
      context: ./envoy
    ports:
      - '8080:8080'
    networks:
      - bitloops

volumes:
  bl-mongo_data:
  bl-nats_data:
  bl-postgres_data:

networks:
  bitloops:
